server {
    listen 127.0.0.1:8080;

    server_name localhost;

    root ./srcs/www/;
    index index.html;

    client_max_body_size 10000000;

    error_page 404 ./srcs/www/404.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /uploads {
        allow_methods GET POST DELETE;
        root ./srcs/www;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./srcs/www;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .sh /bin/bash;
    }

    location /images {
        allow_methods GET;
        root ./srcs/www;
        autoindex on;
    }
}

