server {
    listen 127.0.0.1:8080;

    server_name localhost;

    root ./srcs/www;
    index index.html index.htm;

    client_max_body_size 100000;

    error_page 404 ./srcs/www/404.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /upload {
        allow_methods POST;
        root ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www/cgi-bin;
        cgi_extension .py /usr/bin/python3;
    }

    location /images {
        allow_methods GET;
        root ./www/images;
        autoindex on;
    }
}
