server {
    listen 8080;                        # Port d'écoute
    host 127.0.0.1;                     # Interface réseau
    server_name localhost;              # Nom du serveur
    max_body_size 10M;                  # Limite pour les Uploads (413 Payload Too Large)

    # Page d'erreur par défaut
    error_page 404 ./www/404.html;

    # Route pour les fichiers statiques (Le coeur de ton GET)
    location / {
        root ./www;                     # Dossier racine sur ton disque
        methods GET;                    # Méthodes autorisées
        index index.html;               # Fichier par défaut
        autoindex on;                   # Activer la liste des fichiers si pas d'index
    }

    # Route pour les uploads (Le coeur de ton POST/DELETE)
    location /uploads {
        root ./www/uploads;
        methods GET POST DELETE;
        upload_dir ./www/uploads/tmp;   # Où stocker les fichiers reçus
    }

    # Route pour le CGI (Le coeur de ton moteur dynamique)
    location /cgi-bin {
        root ./www/cgi-bin;
        methods GET POST;
        cgi_path /usr/bin/python3;      # Chemin vers l'interpréteur
        cgi_ext .py;                    # Extension cible
    }
}
